brew 'mise'
brew 'postgresql'
brew 'fish'

cask 'ghostty'
cask 'rectangle'
cask 'jetbrains-toolbox'
cask 'microsoft-teams'
cask 'postman'
cask 'signal'
cask 'google-chrome'
cask 'pomatez'
cask 'viber'
cask 'ngrok'
